feat: 댓글 관리 기능 구현 - CRD [ISSUE-11]
woowacourse-teams/2020-welcome-korea pull request #102
Opened 2020-08-04 15:39 UTC by aegis1920

**이슈 번호**

resolved: #11 

**작업 내용**

1. 댓글 CRD
2. Image와 비슷한 형식으로 구현했습니다 :)

**테스트 작성 여부**

- [X] Test case

**주의 사항**

2020-08-04 22:10 UTC, ttkmw approved these changes
수고하셨슴다~!

2020-08-04 22:10 UTC, ihoph commented on back-end/legeno-around-here/src/main/resources/logback-spring.xml
> +  <property name="ERR_LOG_FILE_NAME" value="err_log"/>
이 부분은 지난번에 오히려 밑에 있는걸 위로 올리지 않았었나여??
확인 부탁해요~

2020-08-05 01:52 UTC, jamie9504 requested changes
리뷰 남겨놨습니다~!

2020-08-05 01:52 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Comment.java
> +    @Lob
`@Lob`으로 관리하는 이유가 있나요?

2020-08-05 01:52 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Post.java
> +
위 메서드는 편의 메서드로 보이는데요,

이렇게 되면 기존에 있던 comments의 comment들은 신규 comment가 추가되지 않은 상태의 Post를 가지고 있게 될 것 같습니다 :)
하지만, 기존의 comments들의 Post를 사용해 comments에 접근하는 일이 없을 것 같고, 없다면 문제가 없을 것 같아요~!

2020-08-05 01:52 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
호옥시 가능하시면 이 부분 posts로 바꿔주시면 좋을 것 같네요! + `FetchType.LAZY`

2020-08-05 01:52 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +
이것도 `FetchType.LAZY`면 좋을 것 같아요!

2020-08-05 01:52 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/CommentService.java
> +    @Transactional(readOnly = true)
find는 Transactional을 안붙여도 된다고 생각했는데,
`readOnly=true` 속성을 가진 Transactional이랑, 붙이지 않는 것의 차이점은 무엇인지 궁금하네요!

2020-08-05 01:52 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
> +    public Post findNotDeletedPost(Long id) {
이 친구는 왜 public 인가요?

2020-08-05 01:52 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/PostAcceptanceTest.java
> +    @MockBean
사이 한 칸 띄워주면 좋을 것 같아요!

2020-08-05 01:52 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/controller/PostControllerTest.java
>      @MockBean
애너테이션 때문에 한 칸을 띄워주면 보기 좋을 것 같아요!

2020-08-05 07:04 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/resources/logback-spring.xml
> +  <property name="ERR_LOG_FILE_NAME" value="err_log"/>
IDE에 있는 정렬 기능을 쓰다보니 다시 아래로 내려갔네요ㅠㅠ 다시 위로 올리겠습니다!

2020-08-05 07:14 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Comment.java
> +    @Lob
많은 양의 문자열을 넣어줄 때 CLOB이라는 타입으로 매핑해주기 위해서 입니다! 양이 적다면 안 써줘도 상관없지만 아직 몇 글자인지 정확히 정해지지 않았기 때문에 사용했습니다 :)

2020-08-05 07:20 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
넵 바꿨습니다! FetchType.LAZY는 어떤 부분을 말씀해주신 건가요?

2020-08-05 07:21 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +
`@OneToMany`는 디폴트가 `FetchType.LAZY` 가 아닌가요??

2020-08-05 07:23 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/CommentService.java
> +    @Transactional(readOnly = true)
`readOnly=true` 속성을 사용하면
- 트랜잭션을 읽기 전용으로 설정할 수 있다.
 - 성능을 최적화하기 위해 사용할 수도 있고 특정 트랜잭션 작업 안에서 쓰기 작업이 일어나는 것을 의도적으로 방지하기 위해 사용할 수도 있다. 
 - 일부 트랜잭션 매니저의 경우 읽기전용 속성을 무시하고 쓰기 작업을 허용할 수도 있기 때문에 주의해야 한다. 
 - 일반적으로 읽기 전용 트랜잭션이 시작된 이후 INSERT, UPDATE, DELETE 같은 쓰기 작업이 진행되면 예외가 발생한다. 

출처: https://goddaehee.tistory.com/167

2020-08-05 07:25 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/PostAcceptanceTest.java
> +    @MockBean
넵 조언 감사합니닷 :)

2020-08-05 07:26 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/controller/PostControllerTest.java
>      @MockBean
넵넵! 조언 감사합니다!!

2020-08-05 07:29 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
> +    public Post findNotDeletedPost(Long id) {
같은 패키지 안의 다른 클래스에서 사용하기 위해 public으로 바꿨습니다!

2020-08-05 08:04 UTC, Hamliet reviewed
수고하셨습니다. 빙봉! 간단한 코멘트 남겼으니 확인 부탁드려요~

2020-08-05 08:04 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Comment.java
> +    private static final int MAX_LENGTH = 20;
댓글 20자는 너무 짧지 않을까요?

2020-08-05 08:04 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/CommentService.java
> +        Comment comment = findNotDeletedComment(commentId);
findComment와 fineNotDeletedComment가 같은 것 같은데 함수를 나눈 이유가 있을까요?

2020-08-05 08:04 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/controller/UserControllerTest.java
> -import static wooteco.team.ittabi.legenoaroundhere.utils.constants.UserTestConstants.TEST_MY_EMAIL;
*저번에 놓친 피드백*
TEST_MY_NAME은 TEST_ANOTHER_NAME과 대응될때만 MY가 의미가 있는데, 
대부분의 테스트에서 MY의 의미가 없는 것 같습니다. TEST_NAME으로 하는 것이 어떨까요?

2020-08-05 08:08 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Comment.java
> +    private static final int MAX_LENGTH = 20;
저희 Post도 20자긴 합니다 ㅋㅋ 추후에 바꾸면 될 것 같아서 아직 바꾸지 않았습니다 :)

2020-08-05 08:12 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/CommentService.java
> +        Comment comment = findNotDeletedComment(commentId);
`findNotDeletedComment()`는 `Comment` 도메인을 넘겨주고, `findComment()`는 `CommentResponse`를 넘겨줍니다!
`findNotDeletedComment()`는 `deleteComment()`에서 도메인의 상태만 바꿔주는 역할을 하기 때문에 나눴습니다 :)

2020-08-05 08:20 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/controller/UserControllerTest.java
> -import static wooteco.team.ittabi.legenoaroundhere.utils.constants.UserTestConstants.TEST_MY_EMAIL;
범용적으로 사용하려면 MY를 빼는 게 더 적절해보이네요! 적용하겠습니다 :)

2020-08-07 06:37 UTC, Hamliet approved these changes
수고하셨습니다 빙봉! 이만 Approve 할게요~

2020-08-07 07:00 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Comment.java
> +    @Lob
추후에 도메인 관련 정책 얘기할 때 다시 논해보면 좋을 것 같네요!

2020-08-07 07:07 UTC, jamie9504 approved these changes
이만 어프로브합니다. 고생하셨어요!

2020-08-07 07:10 UTC, merged