feat: 회원 정보 조회 / 회원 탈퇴 구현 [ISSUE-9]
woowacourse-teams/2020-welcome-korea pull request #103
Opened 2020-08-05 04:40 UTC by Hamliet

**이슈 번호**

resolved: #9 

**작업 내용**

1. 회원 정보 조회 구현
2. 회원 탈퇴 구현

**테스트 작성 여부**

- [X] Test case

**주의 사항**

2020-08-05 10:36 UTC, ttkmw approved these changes
수고하셨습니다~

약간의 리뷰 남겼는데 확인 부탁드려요
그리고 yarn 관련 파일은 gitignore에 넣어도 되는 것인지 한번 확인 부탁드립니다~!

2020-08-05 10:36 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/UserController.java
> +    @CrossOrigin
다른 pr에서 CrossOrigin 빼주시지 않았나여?? 
제가 어떨 때 CrossOrigin 쓰는건지 잘 몰라서 하는 게 맞는건지 확인 부탁드려요~~

2020-08-05 10:36 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Role.java
> +    private final String roleName;
good~~

2020-08-07 06:50 UTC, aegis1920 approved these changes
구현하시느라 수고 많으셨습니다!

2020-08-07 06:50 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +        User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
전역으로 된 SecurityContextHolder를 커스텀 인터페이스로 빼면 Spring의 의존성 주입을 활용할 수 있어 테스트에도 더 편할 것 같은데요! 아래 출처 남겨놓겠습니다 :)

출처 : https://www.baeldung.com/get-user-in-spring-security#interface

2020-08-07 07:14 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +        User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
퍼사드 패턴이란게 있었네요! 한 번 반영해보겠습니다!! :)
https://lktprogrammer.tistory.com/42

2020-08-07 07:23 UTC, jamie9504 requested changes
코드 관련해서 아주 간단한 코멘트만 남겨봤어요!
확인하시고 같이 얘기해보면 좋을거같아요~!

2020-08-07 07:23 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/UserController.java
> +        return ResponseEntity.ok(userService.updateUser(userRequest));
Service에 요청을 한 것을 담아 보내는 로직인데,

가독성 면에서 분리하는 것은 어떨지 같이 생각해보면 좋을 것 같아요!

2020-08-07 07:23 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +        PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
이 부분 필드 변수로 빼도 될 것 같아요!

2020-08-07 07:23 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +            .setPassword(new Password(passwordEncoder.encode(userUpdateRequest.getPassword())));
User에 Update 메서드를 작성해서 setter 여러 개 대신 한 번에 입력받아도 좋을 것 같아요!

& PasswordEncoder로 encoding한 부분까지를 변수로 빼보면 어떨까요?

2020-08-08 03:08 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/UserController.java
> +        return ResponseEntity.ok(userService.updateUser(userRequest));
우선 아래 처럼 적용해두겠습니다 :)
```
ResponseEntity
    .ok(userService.updateUser(userRequest));
```

2020-08-08 03:08 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +            .setPassword(new Password(passwordEncoder.encode(userUpdateRequest.getPassword())));
반영하겠습니다 !! :)

2020-08-08 05:09 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +        PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
반영하겠습니다 !

2020-08-08 07:20 UTC, aegis1920 approved these changes
피드백 반영해주셔서 감사합니다 👍
사소한 피드백 몇 개 드렸는데 먼저 Approve 해도 될 것 같아요ㅎㅎ
수고하셨습니다!!

2020-08-08 07:20 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/UserAcceptanceTest.java
> +     * ======= >>>>>>> feat: 조회/탈퇴 인수테스트 작성 Given 로그인이 되어있는 상태이다. When 회원 탈퇴 요청을 한다. Then 회원 탈퇴가
요기 주석이지만 충돌난 부분이 남아있네요! 지워주실 수 있을까요?

2020-08-08 07:20 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/UserAcceptanceTest.java
> +        UserResponse userResponseForJoin = findUser(tokenResponseForJoin.getAccessToken());
For을 붙이지 않고 `joinedUserResponse`로 해도 괜찮지 않을까요? 밑에 `updatedUserResponse`가 있어서 일관성 있게 가도 괜찮을 것 같아요 :)

2020-08-08 07:27 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/UserAcceptanceTest.java
> +     * ======= >>>>>>> feat: 조회/탈퇴 인수테스트 작성 Given 로그인이 되어있는 상태이다. When 회원 탈퇴 요청을 한다. Then 회원 탈퇴가
헉 확인 감사합니다!!!

2020-08-08 07:30 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/UserAcceptanceTest.java
> +        UserResponse userResponseForJoin = findUser(tokenResponseForJoin.getAccessToken());
반영했습니다! rebase하다가 다른 분 코드를 반영한 부분인데, 변수명을 더블체크하지 않았네요 확인 감사합니다 :)

2020-08-08 07:54 UTC, yelimkim98 approved these changes
Facade Pattern 에 대해서 기술문서를 써주시는 것도 좋을 것 같아요!
수고하셨습니다!

2020-08-08 07:54 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/config/AuthenticationFacade.java
> +            getContext()
쩜 위치가 이상한거가타요!

2020-08-08 07:57 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/config/AuthenticationFacade.java
> +            getContext()
헉 감사합니다. 수정할게요!!

2020-08-08 10:09 UTC, jamie9504 approved these changes
늦어서 죄송해여~ Approve 하겠습니다!

2020-08-08 10:15 UTC, merged