feat: 글에 좋아요를 누르는 기능 구현
woowacourse-teams/2020-welcome-korea pull request #124
Opened 2020-08-09 11:47 UTC by aegis1920

**이슈 번호**

resolved: #12 

**작업 내용**

1. 글에 대한 좋아요 백엔드 구현
2. LikeCount 불변 객체
3. Post, Like와 User, Like 가 1 : N,  1 : N 의 구조로 되어있으며 단방향 관계로 구현
4. Post가 LikeCount만 갖고 있음

**테스트 작성 여부**

- [X] Test case

**참고 사항**
- Post를 삭제해도 Like는 그대로 남아있음

2020-08-10 11:55 UTC, Hamliet approved these changes
고생하셨습니다 빙봉! AcceptanceTest 분리 감사드려요 ㅠㅠ 👍👍👍
코드 확인했고 Approve 하겠습니다!

2020-08-10 11:55 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/LikeCount.java
> +    private long likeCount;
좋아요가 21억 이상일 경우를 대비한 long타입인가요? 😄

2020-08-10 11:55 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AcceptanceTest.java
> +
76라인은 지워도 될 것 같아요!

2020-08-10 11:55 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AcceptanceTest.java
> +public abstract class AcceptanceTest {
AcceptanceTest 분리👍👍👍👍👍 !!

2020-08-10 11:55 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/PostServiceTest.java
> +    private LikeRepository likeRepository;
60라인 밑에 개행문자 추가 부탁드려요! ㅎㅎ

2020-08-10 14:13 UTC, jamie9504 requested changes
확실히 Like는 갯수가 많은 편이라, 객체 관계로 맺는 것보단 DB로 가져오는게 조금 더 효율적이긴 할 것 같아요 :)

보면서 Like 관련된 설계 관련해서 머릿속으로 자꾸 생각이 많아져서 리뷰가 좀 헤매는 느낌이네요 ㅠ_ㅠ
그래도 잘 읽어주시고 반영할 부분이 있다면 반영해주시면 좋을 것 같아요!

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Post.java
> +    public static final long DEFAULT_LIKE_COUNT = 0L;
이 친구는 왜 public 인가요?

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/LikeCount.java
> +    }
add와 minus가 일단 반의어가 아닌 것 같은 느낌이 들어요! 😢 

그리고 LikeCount를 리턴하면 좀 더 좋은 메서드 명이 있을 것 같은데.. 이 부분은 잘 모르겠네요!

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Post.java
> +    }
상동입니다.

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/State.java
> +    INACTIVATED;
좋아요에서만 사용한다면, LikeState로 빼는 게 확장성이 더 좋지 않나 싶어요!

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/repository/LikeRepository.java
> +    void deleteByPostIdAndUserId(Long postId, Long userId);
하드 Delete가 들어가네요? State 변환이 아니라 정말 삭제를 하는 건가요?

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/LikeService.java
> +        likeRepository.save(new Like(post, user));
Like를 새로 생성할 때, post에 addLikeCount()를 해주게 하는 방향은 어떨까요?

Like를 눌렀을 때, post.addLikeCount()가 반응하는 것이라고 생각되어서요!

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/LikeService.java
> +        likeRepository.deleteByPostIdAndUserId(post.getId(), user.getId());
delete를 하나요?(상동)

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Like.java
> +    private State state;
이 친구가 PUBLISHED를 갖는게 아닌 이 둘 중 하나를 가져야 한다고 생각해요 `ACTIVATED`, `INACTIVATED`.

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/LikeService.java
> +        return LikeResponse.of(post.getLikeCount().getLikeCount(), State.INACTIVATED);
. 두개보다는 가져오는 메서드를 만들어주면 좋을 것 같아요.
위에서 delete를 하지 않고 상태를 바꿔준다면, like에서 State를 가져와도 괜찮겠네요!

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
> +            .of(savedPost.getLikeCount().getLikeCount(), State.INACTIVATED);
DB를 사용하지 않고 만들어낼 수 있다면 PostResponse에 넣는 것도 고려해보면 좋을 것 같네요!

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
>      }
LikeService의 메서드명과 동일하게 맞추면 좋을 것 같아요!(뭐가 메인이던..)

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
> +                .of(post,
`.of(post,`까진 올려도 될 것 같아요!

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AcceptanceTest.java
> +    }
protected도 괜찮겠네요!

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/PostAcceptanceTest.java
> +
공백!?

2020-08-10 14:13 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/CommentServiceTest.java
>      @Autowired
공란이 시급합니다!

2020-08-11 03:37 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/LikeCount.java
> +    private long likeCount;
넵ㅎㅎ 전체 인구가 60억이라서 혹시 모를 상황에 대비해 long 타입으로 줬습니다 :)

2020-08-11 03:38 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AcceptanceTest.java
> +
넵 지웠습니다!

2020-08-11 03:57 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/PostServiceTest.java
> +    private LikeRepository likeRepository;
추가했습니다!

2020-08-11 04:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Post.java
> +    public static final long DEFAULT_LIKE_COUNT = 0L;
자동으로 만들어줄 때 public으로 만들어져서 못 봤네요! Post 말고도 다른 도메인도 private으로 만들어야 될 것 같습니다ㅎㅎ 조언 감사합니다!

2020-08-11 04:42 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/LikeCount.java
> +    }
오 동의합니다! 수를 증가시키는 느낌이라 `plus`와 `minus`로 수정했습니다!

2020-08-11 04:42 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Post.java
> +    }
수정했습니다~!

2020-08-11 05:57 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/State.java
> +    INACTIVATED;
Like에만 쓰이는 LikeState로 분리하니 확장성이 더 좋게 된 것 같아요! 다만 이렇게 되니 State는 Post와 Comment에만 쓰이게 될 것 같네요ㅎㅎ Enum 명은 추후에 생각해보도록 하죠 :)

2020-08-11 06:14 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/repository/LikeRepository.java
> +    void deleteByPostIdAndUserId(Long postId, Long userId);
좋아요는 글이나 댓글과는 다르게 사용자 입장에서 삭제하는 것이 없기 때문에 State 변환을 해주지 않아도 된다고 생각했습니다 :)

2020-08-11 08:43 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/LikeService.java
> +        return LikeResponse.of(post.getLikeCount().getLikeCount(), State.INACTIVATED);
수정했습니다!

2020-08-11 08:44 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/Like.java
> +    private State state;
오 항상 PUBLISHED만 쓰다보니 헷갈렸네요! 감사합니다 :)

2020-08-11 08:44 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/LikeService.java
> +        likeRepository.deleteByPostIdAndUserId(post.getId(), user.getId());
넵 위에 이유를 적어놓았습니다 :)

2020-08-11 08:45 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/LikeService.java
> +        likeRepository.save(new Like(post, user));
이 부분은 추후에 적용하도록 하겠습니다 :)

2020-08-11 08:46 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
>      }
PostService와 동일하게 맞췄습니다 :)

2020-08-11 08:47 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
> +                .of(post,
들여쓰기가 저렇게 됐네요;;  수정했습니다 :)

2020-08-11 08:47 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AcceptanceTest.java
> +    }
수정했습니다 ~

2020-08-11 08:48 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/PostAcceptanceTest.java
> +
삭제했습니다~

2020-08-11 08:48 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/CommentServiceTest.java
>      @Autowired
머지시키면서 수정했습니다 :)

2020-08-12 07:18 UTC, jamie9504 requested changes
리뷰를 조금 더 달아봤습니다! 확인 부탁드려요~

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/post/Content.java
> +}
사용하지 않는 객체면 제거해주세요!

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/post/like/Like.java
> +public class Like extends BaseEntity {
`PostLike` or `PostZzang` 으로 바꾸는 건 어떨까요?

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/post/like/Like.java
> +    public boolean isSameUser(User user) {
isSameCreator가 더 좋을 것 같은데 어떻게 생각하시나요?

Like의 Creator와 비교를 하게 되는 느낌이라서요~!

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/ServiceTest.java
> +@TestPropertySource("classpath:application-test.properties")
@TestPropertySource를 사용하는 이유가 있나요?

test 코드에 application.properties를 사용하지 않는 이유가 궁금합니다!

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/controller/UserControllerTest.java
>      @MockBean
개행문자가 있으면 좋겠어요.

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/CommentAcceptanceTest.java
> +
개행이 없어도 될 것 같아요!

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/utils/ImageUploader.java
> +public class ImageUploader {
Service가 아니라 Component인 이유가 있을까요? 궁금하네요!

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
> +        return new ArrayList<>(commentRepository.findAllByPostIdAndStateNot(postId, State.DELETED));
new Array<>()를 해준 이유가 있을까요?

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/post/Post.java
> +    public Like findLikeBySameUser(User user) {
`existLikeBy`처럼 `findLikeBy`까지만 해도 괜찮을 것 같아요~!

2020-08-12 07:18 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
> +    }
이미 post와 user를 알고 있는데, Repository에서 가져올 필요가 있을까요?
, findLike를 Post에 일임해도 좋을 것 같네요.

`getLikeState(User user)`이런 식으로요!

2020-08-12 07:19 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/post/Content.java
> +}
넵넵!

2020-08-12 07:20 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/post/like/Like.java
> +    public boolean isSameUser(User user) {
Creator가 확실히 더 눈에 잘 들어오네요 감사합니다 👍

2020-08-12 07:28 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/post/like/Like.java
> +public class Like extends BaseEntity {
회의 후 postZzang으로 결정되었습니다!

2020-08-12 07:32 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/ServiceTest.java
> +@TestPropertySource("classpath:application-test.properties")
그냥 application.properties를 써도 됐었군요! 조언 감사합니다 :)

2020-08-12 07:36 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/controller/UserControllerTest.java
>      @MockBean
작업했던 부분이 아니라 못 봤습니다ㅠ 수정했습니다!

2020-08-12 07:37 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/CommentAcceptanceTest.java
> +
수정했습니다~

2020-08-12 07:40 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/utils/ImageUploader.java
> +public class ImageUploader {
다른 서비스에 붙어서 S3에 업로드하는 기능만 하기때문에 서비스레이어에 있기보다는 유틸성 클래스에 가깝다는 생각이 들어서 @Service가 아닌 @Component로 수정했습니다 :)

2020-08-12 07:48 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
> +        return new ArrayList<>(commentRepository.findAllByPostIdAndStateNot(postId, State.DELETED));
인텔리제이가 추천해준 자동완성으로 위와 같이 작성됐었습니다! 아마 null 때문에 그 때 추천해줬던 것 같은데 로직이 바뀌면서 수정사항이 생겼던 것 같습니다 :) 지워도 될 것 같아요!

2020-08-12 07:49 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/post/Post.java
> +    public Like findLikeBySameUser(User user) {
existLikeBy와 동일하게 맞췄습니다 :)

2020-08-12 08:11 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/PostService.java
> +    }
post에서 찾아오도록 바꿔보았습니다 :)

2020-08-12 08:57 UTC, jamie9504 approved these changes
고생하셨어요~!

2020-08-12 08:59 UTC, merged