feat: API 문서화
woowacourse-teams/2020-welcome-korea pull request #127
Opened 2020-08-10 09:33 UTC by aegis1920

**이슈 번호**

resolved: #93 

**작업 내용**

1. Swagger API 적용

**테스트 작성 여부**

- [ ] Test case

**참고 사항**
- 스프링 시큐리티 Config 안에 Swagger 경로 추가

2020-08-10 12:09 UTC, Hamliet approved these changes
빠르고 깔끔하게 잘 구현해 주셨네요!
내일 데일리 때 간단히 설명해 주시면 좋을 것 같아요 :)
Approve 하겠습니다!

2020-08-10 12:37 UTC, jamie9504 requested changes
빠른 적용 Good이에요! build.gradle 부분만 확인 부탁드려요!

2020-08-10 12:37 UTC, jamie9504 commented on back-end/legeno-around-here/build.gradle
> +    compile 'io.springfox:springfox-swagger-ui:2.9.2'
implementation은 어떨까요?
https://hack-jam.tistory.com/13

2020-08-11 01:38 UTC, aegis1920 commented on back-end/legeno-around-here/build.gradle
> +    compile 'io.springfox:springfox-swagger-ui:2.9.2'
자세한 정보 감사합니다! 조금 더 찾아봤어요!

- implementation: 의존 라이브러리 수정시 본 모듈까지만 재빌드
    - 본 모듈을 의존하는 모듈은 해당 라이브러리의 api 를 사용할 수 없음
- api: 의존 라이브러리 수정시 본 모듈을 의존하는 모듈들도 재빌드
    - 본 모듈을 의존하는 모듈들도 해당 라이브러리의 api 를 사용할 수 있음
- compileOnly: compile 시에만 빌드하고 빌드 결과물에는 포함하지 않음
    - runtime 시 필요없는 라이브러리인 경우 (runtime 환경에 이미 라이브러리가 제공되고 있는가 하는 등의 경우)
- runtimeOnly: runtime 시에만 필요한 라이브러리인 경우
- annotationProcessor: annotation processor 명시 (gradle 4.6)
    - Annotation processing 이 필요없다고 예측되는 경우 빌드 제외

출처 : https://tjandroid.blogspot.com/2018/11/api-implementation.html

2020-08-11 01:40 UTC, yelimkim98 approved these changes
고생하셨어용 ㅎㅎ!

2020-08-11 01:40 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/config/SwaggerConfig.java
> +    public static final String BASE_PACKAGE_CONTROLLER_NAME = "wooteco.team.ittabi.legenoaroundhere.controller";
CONTROLLER_BASE_PACKAGE_NAME 은 어떤가요.. ㅎㅎ

2020-08-11 01:44 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/config/SwaggerConfig.java
> +    public static final String BASE_PACKAGE_CONTROLLER_NAME = "wooteco.team.ittabi.legenoaroundhere.controller";
알아보기 쉽게 `CONTROLLER_PACKAGE_NAME`으로 수정했습니다! 조언 감사합니다 👍

2020-08-11 01:51 UTC, jamie9504 approved these changes

2020-08-11 01:51 UTC, merged