feat: 사용자 프로필사진 관리 기능 추가
woowacourse-teams/2020-welcome-korea pull request #236
Opened 2020-08-18 01:14 UTC by jamie9504

**이슈 번호**

resolved: #223 

**작업 내용**

1. 사용자 프로필사진 관리 기능 추가
2. 기존 ZzangState 필드 제거 - Merge 전 DB 작업 필수

**테스트 작성 여부**

- [X] Test case

**주의 사항**

2020-08-18 10:45 UTC, yelimkim98 approved these changes
수고하셨습니다~ 보잘것없는 코멘트 몇줄 남기고 갑니다 하핳

2020-08-18 10:45 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/utils/ImageUploader.java
> +        validateImage(multipartFile);
여기 사이에 엔터 한번 넣어주시면 어떨까요?! 이미지랑 유저 문맥상 나눠보면 어떨까 해서요~

2020-08-18 10:45 UTC, yelimkim98 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/UserServiceTest.java
> +    void createUser_DuplicationEmail_ThrownException() {
DuplicateEmail 어떨까요~~??ㅎ

2020-08-18 14:00 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/UserServiceTest.java
> +    void createUser_DuplicationEmail_ThrownException() {
👍 좋습니다! DuplicatedEmail도 괜찮은 것 같아요! 추천 감사합니당!

2020-08-18 14:14 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/utils/ImageUploader.java
> +        validateImage(multipartFile);
좋아요! validate도 하나로 합쳐버렸습니다!

2020-08-18 14:34 UTC, Hamliet reviewed
안녕하세요 제이미! 코멘트 남겼으니 확인 부탁드려요~!

2020-08-18 14:34 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    private UserImage image = null;
userImage 대신 image를 사용하신 이유가 있나요?

2020-08-18 14:34 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    private List<String> roles = Collections.singletonList(Role.USER.getRoleName());
유저 권한을 단 하나로 제한하는 것은 확장성을 닫는 느낌이 듭니다. 지금은 User가 Role.User만 사용하고 있지만 추후에 부가적인 옵션이 생기고 Role이 변경된다면 여러개의 권한을 넣을수도 있을 것 같습니다.

2020-08-18 14:34 UTC, Hamliet commented on back-end/legeno-around-here/src/main/resources/application-local.properties
> +spring.servlet.multipart.max-request-size=50MB
?_?

2020-08-18 14:34 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserCreateRequest.java
> +    }
User에 대한 builder가 Dto에 있는게 맞을까 고민됩니다.  toUser를 사용해서 데이터 전송간에 변환이 필요할 때 사용하는거라면 모르겠는데 서비스에 있던 빌더를 분리하기 위해서 만들어진 함수인데 dto가 그 역할을 하는 것이 맞는것인가 싶습니다. dto는 단순히 데이터만 옮기면 좋을 것 같거든요. 그렇다 보니까 파라미터로 Area를 받는 부분도 어색해보입니다!

2020-08-18 14:34 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +        userCreateRequest.setPassword(passwordEncoder.encode(userCreateRequest.getPassword()));
userCreateRequest의 의미가 유저가 요청한 생성에 대한 정보인데 유저가 요청한 값이 아닌 우리가 가공한 값을 set하는게 이상해 보여요. 아래 builder를 userCreateRequest로 만들어서 그런 것 같은데, 저는 빌더 자체가 User이기 때문에 위에서 말한 것 처럼 dto에 있는것보단 기존처럼 서비스 로직에 있는 것이 더 깔끔해 보입니다.

2020-08-18 14:40 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    private UserImage image = null;
User에 있는 image라서요! 중복이라고 생각했어요! 마치 UserEmail 같은 느낌,,
(DB에는 들어가지 않는 부문)

2020-08-18 14:40 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/resources/application-local.properties
> +spring.servlet.multipart.max-request-size=50MB
?ㅁ?

2020-08-18 14:47 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    private List<String> roles = Collections.singletonList(Role.USER.getRoleName());
👍 👍 👍 👍 👍  ArrayList로 감싸두었습니다~!!

2020-08-18 14:56 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserCreateRequest.java
> +    }
흠.. 저는 몇 번 이렇게 써왔어서 큰 생각없이 사용했네요!
DTO는 확실히 로직이 없는 게 좋을 것 같아서~ 전반적인 부분 다시 확인하고 리팩해서 올릴게용!

2020-08-19 02:43 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserCreateRequest.java
> +    }
팀원끼리 상의한 결과

1. DTO에서 로직이 들어가는 가공하는 부분은 assembler로 뺀다.
2. 만드는대상명assembler
3. 패키지는 dto 하위

리팩하겠습니다.

2020-08-19 03:44 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +        userCreateRequest.setPassword(passwordEncoder.encode(userCreateRequest.getPassword()));
위와 동일하게 리팩하겠습니다~!

2020-08-19 06:54 UTC, aegis1920 requested changes
안녕하세요 제이미! 늦어서 죄송합니다ㅠ
몇 가지 피드백 드렸으니 확인해주세요 :)

2020-08-19 06:54 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/PageableAssembler.java
> +            System.out.println(page);
sout을 찍어주는 이유가 있을까요?

2020-08-19 06:54 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/UserImage.java
> +    public void setInitUser(User user) {
setInitUser가 update시에 일어나기 때문에 init이 어울리지 않는 느낌인데요! 개인적으로는 단순하게 setUser로 가도 좋을 것 같아요 :)

2020-08-19 06:54 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserAssembler.java
> +            .email(null)
email에 null을 넣기보다 해당 줄을 빼면 가독성면에서 더 좋아질 것 같아요!

2020-08-19 06:54 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    public User(String email, String nickname, String password, Area area, UserImage image) {
좋은 정보 공유합니다 :)
https://cheese10yun.github.io/spring-builder-pattern/

2020-08-19 06:54 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserUpdateRequest.java
> +    private Long imageId;
원래 있던 프로필 이미지에서 다른 이미지로 바꾸는 경우에는 해당 이미지의 id를 어떻게 보내나요? 이미지를 바꿀 때마다 해당 이미지 요청을 보내는 건가요?

2020-08-19 06:54 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/UserController.java
> +            .created(URI.create("/user-images" + userImage.getId()))
`"/user-images/"`로 뒤에 `/`를 붙여야 하지 않을까요?

2020-08-19 06:54 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +    private static final PasswordEncoder PASSWORD_ENCODER = new BCryptPasswordEncoder();
good! 👍

2020-08-19 06:54 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/utils/ImageUploaderTest.java
> +public class ImageUploaderTest extends ServiceTest {
User에 대한 이미지가 추가되면서 테스트케이스를 더 추가해주셨네요 👍 👍

2020-08-19 06:54 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/UserAcceptanceTest.java
> +        assertThat(userResponse.getImage()).isNotNull();
프로필 사진 등록에 대한 부분은 '회원지역관리'라는 인수테스트보다 '회원관리'라는 인수테스트에 들어가는 게 맞는 것 같아요! 그리고 가능하다면 프로필 이미지 수정을 할 때 이 기본 이미지일 때와 이미지가 이미 있을 때의 경우를 나눠서 하면 더욱 좋을 것 같아요 :)

2020-08-19 09:03 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/PageableAssembler.java
> +            System.out.println(page);
앗.... 아니요!! 지워버리겠습니다!

2020-08-19 09:04 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/UserImage.java
> +    public void setInitUser(User user) {
오 둘 사이에서 고민했는데, 의견 감사합니당!

2020-08-19 09:05 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserUpdateRequest.java
> +    private Long imageId;
네, 이미지 등록할 때마다 이미지를 먼저 등록하고 나서, 수정시에 ID를 보내줍니다!

2020-08-19 09:05 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/UserController.java
> +            .created(URI.create("/user-images" + userImage.getId()))
그저 빛...! 감사합니다!!

2020-08-19 09:10 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/UserAcceptanceTest.java
> +        assertThat(userResponse.getImage()).isNotNull();
엇 그렇네요~!! 지역관리에 들어가있었군요!

변경해두겠습니당!

2020-08-19 09:43 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    public User(String email, String nickname, String password, Area area, UserImage image) {
응용해볼께요!

2020-08-19 09:46 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserAssembler.java
> +            .email(null)
오히려 명시를 해준다는 생각이었는데 없는게 더 깔끔해보이는군요! 지웠습니다!

2020-08-19 10:46 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserUpdateRequest.java
> +    private Long imageId;
그러면 사용자 입장에서 이미지를 바꿀 때마다 S3에 전부 올라가나요?

2020-08-19 10:54 UTC, Hamliet approved these changes
수고하셨습니다. 이만 Approve할게요!

2020-08-19 11:14 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserUpdateRequest.java
> +    private Long imageId;
네 맞습니다~! (깃헙 방식과 동일)

추후에 User가 매핑되지 않은 UserImage를 모두 삭제하는 배치성 API를 만들어주면 될 것 같아요!

2020-08-19 11:35 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserUpdateRequest.java
> +    private Long imageId;
매번 바꿀 때마다 S3에 올라간다면 그만큼 S3를 사용하는 비용도 늘어날텐데 사용자에게 바꿀 수 있는 수를 제한하기도 애매하지 않나요?

2020-08-19 12:24 UTC, aegis1920 approved these changes
수고하셨습니다 천제이미! 👍

2020-08-19 12:33 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserUpdateRequest.java
> +    private Long imageId;
회의를 통한 내용)

일단은 사진을 첨부할 때, 백엔드로 사진들을 보내고, URI+ID등을 리턴받아 글이나 프로필 등록/수정시 ID를 보내주는 것으로 얘기했습니다.

사용하지 않는 사진에 대한 삭제는 추후에 고려해봐야 할 것 같습니다.

2020-08-19 12:33 UTC, merged