feat: 이메일 인증 [ISSUE-3]
woowacourse-teams/2020-welcome-korea pull request #280
Opened 2020-08-21 18:11 UTC by Hamliet

**이슈 번호**

resolved: #3 

**작업 내용**

1. 인증번호 생성, db저장, 메일전송하는 기능 구현
2. 인증번호를 체크하는 기능 구현

**인증 방식**

1. 인증 번호를 생성하여 db에 저장, 메일로 전송함
2. 메일에 주어진 링크를 클릭하면 링크에 포함된 유저이메일, 인증번호로 체크를 시도함
3. DB에 있는 인증번호화 링크로 요청한 인증번호가 일치하면 User Entity 의 isAuthenticatedByEmail을 true로 바꿔줌

**테스트 작성 여부**

- [ ] Test case

**주의 사항**
1. data.sql 에 종속적인 테스트로 변경되었습니다. (이메일 인증이 완료된 유저 필요)
2. 머지 후 server쪽에 mail sender의 정보 등록 필요

**프론트 구현 시 유의 사항**
1. 회원 가입 시 인증 메일을 보내도록 프론트에 구현해야함 
2. 로그인 요청시 이메일 인증이 안돼있을 경우 이메일 인증이 필요하다는 에러 (500) 내려줌
3. 해당 에러를 받을 경우 "이메일 인증을 완료해주세요" 문구가 나타나는 페이지로 리다이렉트 필요

2020-08-22 05:17 UTC, jamie9504 requested changes
인수테스트 전반적인 수정에 고생 많이 하신 게 눈에 보이네요~!

몇 개 리뷰 남겨놓았으니 참고 부탁드려요~!

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/config/WebSecurityConfig.java
> +            .antMatchers("/mail-auth").permitAll()
하나로 합체해도 될 것 같긴 한데... 취향 차이일지도 모르겠네요~!

```suggestion
                "/webjars/**",
                "/join",
                "/login",
                "/mail-auth").permitAll()
```

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/MailAuthController.java
> +    }
롬복을 활용해볼까요?

```suggestion
@AllArgsConstructor
public class MailAuthController {

    private final MailAuthService mailAuthService;
```

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/mailauth/AuthNumber.java
> +    }
요기도 롬복을 활용해볼까요?

```suggestion
@AllArgsConstructor
@Getter
@Setter
@EqualsAndHashCode
public class AuthNumber {

    private int AuthNumber;
```

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/mailauth/MailAuth.java
> +    }
getter가 아닌, authNumber에게 위임해보는건 어떨까요?

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/MailAuthCheckRequest.java
> +    private int authNumber;
외부에서 들어오는 값이면 null일 경우를 대비하여 포장값인게 좋지 않을까요? `Integer`
(기본 값의 차이..)

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/mailauth/AuthNumber.java
> +    private int AuthNumber;
int가 아닌 Integer를 가지고 있어야 하지 않을까요? (DB에서 오는 정보)

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +    UserRepository userRepository;
접근제어자가 사라졌어요~!

```suggestion
    private final JavaMailSender javaMailSender;
    private final MailAuthRepository mailAuthRepository;
    private final UserRepository userRepository;
```

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +    private static final int AUTH_NUMBER_MIN = 100000;
`_`를 써주면 가독성을 확보할 수 있죠!

```suggestion
    private static final int AUTH_NUMBER_MIN = 100_000;
```

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/infra/JwtTokenDecoderTest.java
> +            .createToken("notexist_" + TEST_USER_EMAIL, Collections.singletonList("ROLE_USER"));
테스트 코드 전반적으로 `CommentServiceTest.java` 처럼 PREFIX를 상수로 빼면 어떨까요~!? 통일감을 주면 좋을 것 같아서요!

아니면 PREFIX + USER_EMAIL을 상수로 빼도 좋을 것 같네요 (매번 안붙여줘도 되니까)

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +            jwtTokenGenerator.createToken(user.getEmailByString(), user.getRoles()));
길면 두 줄로 나눠도 될 것 같아요~!

```suggestion
        String token = jwtTokenGenerator.createToken(user.getEmailByString(), user.getRoles())
        return new TokenResponse(token);
```

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/utils/MailHandler.java
> +    private MimeMessageHelper mimeMessageHelper;
final 선언해주는게 어떨까요!

```suggestion
    private final JavaMailSender javaMailSender;
    private final MimeMessage mimeMessage;
    private final MimeMessageHelper mimeMessageHelper;
```

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +
그 때 라흐가 말씀주신 것처럼 tinyint가 아닌 boolean이어도 될 것 같아요! :>

저는 boolean 타입 변수명에 is를 붙이는건 항상 고민되는 부분이에요.. ㅎㅁㅎ/

By를 빼도 되지 않을까하는건 개인 취향이네용!

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +        return AUTH_NUMBER_MIN + random.nextInt(900000);
매직넘버...?

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +        Random random = new Random();
http://dveamer.github.io/backend/JavaRandom.html 의 `ThreadLocalRandom` 부분을 한 번 읽어보시면 좋을 것 같아요

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +    private void updateUserEmailAuthTrue(Email email) {
뭔가 `updateUserEmailAuthed`(예),,, 같이 풀 수 있을 것 같은데, True False가 메서드 명에 있는게 좋은지 모르겠네요!

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/utils/MailHandler.java
> +    }
통일감..?
```suggestion
    public MailHandler(JavaMailSender javaMailSender) throws MessagingException {
        this.javaMailSender = javaMailSender;
        this.mimeMessage = javaMailSender.createMimeMessage();
        this.mimeMessageHelper = new MimeMessageHelper(mimeMessage, true, "UTF-8");
    }
```

UTF-8은 상수로 빼도 좋겠네요~!

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AcceptanceTest.java
> +            .statusCode(HttpStatus.INTERNAL_SERVER_ERROR.value());
500 에러를 던져주는군요!

2020-08-22 05:17 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AwardAcceptanceTest.java
> +        userId = TEST_USER_ID;
별 건 아니지만, 순서를 바꾸는게 더 읽기 편한 것 같아요!

```suggestion
        userId = TEST_USER_ID;
        TokenResponse token = login(TEST_USER_EMAIL, TEST_USER_PASSWORD);
```

2020-08-22 05:53 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/config/WebSecurityConfig.java
> +            .antMatchers("/mail-auth").permitAll()
일괄되도록 수정했습니다~

2020-08-22 05:54 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/MailAuthController.java
> +    }
수정했습니다~

2020-08-22 05:57 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/mailauth/AuthNumber.java
> +    }
수정했습니다~!

2020-08-22 06:25 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/mailauth/MailAuth.java
> +    }
수정했습니다!

2020-08-22 06:26 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/MailAuthCheckRequest.java
> +    private int authNumber;
반영했습니다!! :)

2020-08-22 06:27 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/mailauth/AuthNumber.java
> +    private int AuthNumber;
반영했습니다!! :)

2020-08-22 06:27 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +    UserRepository userRepository;
감사합니다 ㅎㅎ!

2020-08-22 06:28 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +    private static final int AUTH_NUMBER_MIN = 100000;
👍

2020-08-22 06:33 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/infra/JwtTokenDecoderTest.java
> +            .createToken("notexist_" + TEST_USER_EMAIL, Collections.singletonList("ROLE_USER"));
```
user = createUser(TEST_PREFIX + TEST_USER_EMAIL, TEST_USER_NICKNAME, TEST_USER_PASSWORD);
another = createUser(TEST_PREFIX + TEST_USER_OTHER_EMAIL, TEST_USER_NICKNAME,
            TEST_USER_PASSWORD);
```
과 같이 테스트 안에서 사용되고 있는데요 매번 붙인다기보다는 각 서비스에서 create할 때 한번 붙이거나 위 처럼 사용할때만 붙이고 있습니다! 일단 "notexist_"만 상수로 빼도록 하겠습니다~

2020-08-22 06:37 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +            jwtTokenGenerator.createToken(user.getEmailByString(), user.getRoles()));
반영했습니다! :)

2020-08-22 06:38 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/utils/MailHandler.java
> +    private MimeMessageHelper mimeMessageHelper;
반영했습니다!

2020-08-22 06:46 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +        return AUTH_NUMBER_MIN + random.nextInt(900000);
😲

2020-08-22 06:46 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +        return AUTH_NUMBER_MIN + random.nextInt(900000);
상수로 빼겠습니다.!

2020-08-22 06:48 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +        Random random = new Random();
지금까지 Random만 써봤는데 ThreadLocalRandom 이란것도 있었군요! 반영하였습니다 :)

2020-08-22 06:55 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +
authenticatedEmail 은 인증된 이메일이란 뜻인데,
저는 이메일을 인증한다기 보다는 user를 인증한다고 생각하고 있고 그 방법이 email이라고 생각합니다. 
(user) authenticated by email 인거죠!
우선 authenticatedByEmail 로 바꾸도록 하겠습니다. :)

2020-08-22 07:02 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +    private void updateUserEmailAuthTrue(Email email) {
이메일이 auth 된다기 보다는 이메일인증(emailauth)을 true로 만든 부분인데요, 
그렇기 때문에 updateUserEmailAuthed나 updateUserEmailAuthenticated로 하면 의미가 변할 것 같습니다. (위에서 말씀드린 것처럼 email을 인증한다기 보다는 user를 인증하는 거니까요)
우선 updateUserEmailAuthPassed로 변경했는데 다른 변수명 추천해주시면 반영해보겠습니다!

2020-08-22 23:24 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AcceptanceTest.java
> +            .statusCode(HttpStatus.INTERNAL_SERVER_ERROR.value());
401이 더 좋을까요..?

2020-08-22 23:39 UTC, jamie9504 approved these changes
확인해보면 좋을 코멘트 조금 남겨보고, Approve 합니다 :)

2020-08-22 23:39 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +@Transactional
메서드에 `@Transactional`을 붙여준다면 클래스에서는 붙이지 않아도 됩니다~!

2020-08-22 23:39 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +        random.setSeed(System.currentTimeMillis());
Random은 어디서 쓰이나요?

2020-08-22 23:39 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +    }
아래처럼 메서드를 분리해보는 건 어떨까요?
``` java
    @Transactional
    public void checkAuth(MailAuthCheckRequest mailAuthCheckRequest) {
        Email email = new Email(mailAuthCheckRequest.getEmail());
        MailAuth mailAuth = mailAuthRepository.findByEmail(email)
            .orElseThrow(() -> new NotExistsException("올바르지 않은 이메일입니다."));
        
        validateAuthNumber(mailAuth, mailAuthCheckRequest.getAuthNumber());
        updateUserEmailAuthPassed(email);
    }

    private void validateAuthNumber(MailAuth mailAuth, Integer AuthNumber) {
            if (mailAuth.isDifferentAuthNumber(mailAuthCheckRequest.getAuthNumber())) {
                throw new WrongUserInputException("인증 정보가 일치하지 않습니다.");
            }
    }
```

2020-08-22 23:41 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +@Transactional
저도 원래 메서드만 붙이긴 하는데 PostService쪽 구조를 복사하다가 딸려온 친구 같은데요,
 PostService에는 Class에 붙은 이유가 있을까요?

2020-08-22 23:43 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +        random.setSeed(System.currentTimeMillis());
리팩토링 과정에서 삭제하는 걸 깜빡했습니다! 삭제할게요~

2020-08-22 23:47 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +    }
훨씬 깔끔해졌네요! 반영하겠습니다~!

2020-08-23 00:00 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +@Transactional
PostService에는 리팩터링했을 때 빼는걸 놓친 것 같아서 롬복 리팩터링 하고 있는데 이 때 빼주었어요!

2020-08-23 00:04 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/MailAuthService.java
> +@Transactional
아하 알겠습니다! 확인 감사해요~!

2020-08-23 02:59 UTC, aegis1920 reviewed
간단한 리뷰 남겼습니다! 확인해주세요~

2020-08-23 02:59 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/comment/Comment.java
> +    private final List<CommentZzang> zzangs = new ArrayList<>();
엔티티의 list 필드에 final을 붙이는 이유가 있을까요? 영속성을 가지기 위해서는 final을 붙이지 않아야 하는 것으로 알고 있어서요!

출처 : https://www.objectdb.com/java/jpa/entity/fields

2020-08-23 02:59 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AcceptanceTest.java
> +            .statusCode(HttpStatus.INTERNAL_SERVER_ERROR.value());
로그인 전에 이메일 인증이 안돼서 실패하는 거라면 401이 더 맞다고 생각합니다 :)

2020-08-23 04:43 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/comment/Comment.java
> +    private final List<CommentZzang> zzangs = new ArrayList<>();
Reformat Code를 실행할 때 자동으로 붙은 final인데 평소에는 파일을 빼고 푸시를 했는데 이번에 빼는걸 깜빡했습니다! 해당 부분 수정하겠습니다!!

2020-08-23 04:45 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptance/AcceptanceTest.java
> +            .statusCode(HttpStatus.INTERNAL_SERVER_ERROR.value());
401로 수정하겠습니다! 현재 프론트에서 401일 경우 로그인 페이지로 가는데 해당 부분을 잘 처리해줘야겠네요 :)

2020-08-23 05:24 UTC, aegis1920 approved these changes
수고하셨습니다 라흐~ 👍

2020-08-23 05:31 UTC, merged