feat: 회원가입시 약관 동의 모달 구현
woowacourse-teams/2020-welcome-korea pull request #463
Opened 2020-09-22 06:32 UTC by jamie9504

**이슈 번호**

resolved: #460 

**작업 내용**

1. 이용약관 동의 추가
2. 개인정보 관련 동의 추가

**참고사항**
이슈에 들어가시면 화면 캡쳐를 확인하실 수 있습니다

2020-09-22 10:07 UTC, yelimkim98 reviewed
오오 수고하셨습니다!! 혹시 풀리퀘에 화면캡처 담아주실 수 있을까요?!
화면캡처 확인하면 approve 하겠습니다!

2020-09-22 10:07 UTC, yelimkim98 commented on front-end/legeno-around-here/src/components/pages/JoinPage.js
> +        console.log(termsAgree);
console.log 지워도 될 것 같네요!!

2020-09-22 10:07 UTC, yelimkim98 commented on front-end/legeno-around-here/src/components/signUp/PrivacyModal.js
> +  '개인정보처리시스템에 접속한 기록을 최소 6개월 이상 보관, 관리하고 있으며, 접속 기록이 위변조 및 도난, 분실되지 않도록 보안기능 사용하고 있습니다.';
constants 패키지가 있었던것 같아서 그쪽으로 빼도 괜찮을것 같네요!!
코드가 들어있는 파일과 조금이라도 더 분리되면 좋을것 같아서요!

2020-09-22 10:07 UTC, yelimkim98 commented on front-end/legeno-around-here/src/components/signUp/TermsModal.js
> +  '(시행일) 이 약관은 2020년 09월 22일부터 시행합니다.';
얘도 코드파일과 분리되면 좋을것같아요!

2020-09-22 10:20 UTC, aegis1920 requested changes
안녕하세요 제이미! 몇 가지 피드백과 궁금한 점 남겼습니다 :)
확인해주세요~

2020-09-22 10:20 UTC, aegis1920 commented on front-end/legeno-around-here/src/components/signUp/PrivacyModal.js
> +            label='Multiline'
라벨이 Multiline으로 그대로 박혀있어요! 라벨을 없애도 될 것 같아요 :)

2020-09-22 10:20 UTC, aegis1920 commented on front-end/legeno-around-here/src/components/signUp/TermsModal.js
> +            label='Multiline'
여기도 마찬가지!

2020-09-22 10:20 UTC, aegis1920 commented on front-end/legeno-around-here/src/components/pages/JoinPage.js
> +  };
바로 event.preventDefault()를 해주는데 event 인자를 받는 이유가 따로 있나요?

2020-09-22 10:20 UTC, aegis1920 commented on front-end/legeno-around-here/src/components/signUp/PrivacyModal.js
> +  '개인정보처리시스템에 접속한 기록을 최소 6개월 이상 보관, 관리하고 있으며, 접속 기록이 위변조 및 도난, 분실되지 않도록 보안기능 사용하고 있습니다.';
동의합니다 :)

2020-09-22 10:20 UTC, aegis1920 commented on front-end/legeno-around-here/src/components/signUp/TermsModal.js
> +};
👍 👍

2020-09-23 10:09 UTC, jamie9504 commented on front-end/legeno-around-here/src/components/pages/JoinPage.js
> +        console.log(termsAgree);
앗 확인을 놓쳤었네요!! 제거했습니다! 감사합니다 :)

2020-09-23 10:10 UTC, jamie9504 commented on front-end/legeno-around-here/src/components/signUp/PrivacyModal.js
> +  '개인정보처리시스템에 접속한 기록을 최소 6개월 이상 보관, 관리하고 있으며, 접속 기록이 위변조 및 도난, 분실되지 않도록 보안기능 사용하고 있습니다.';
뺄까 말까 고민을 하다가.. 다시 쓰이지 않아서 그냥 놔뒀었는데 빼는게 더 깔끔하겠네요!

constants 쪽으로 빼냈습니다 :) 감사합니다~!

2020-09-23 10:21 UTC, jamie9504 commented on front-end/legeno-around-here/src/components/signUp/PrivacyModal.js
> +            label='Multiline'
제거했습니다!

2020-09-23 10:22 UTC, jamie9504 commented on front-end/legeno-around-here/src/components/signUp/TermsModal.js
> +            label='Multiline'
제거했습니다~!

2020-09-23 10:23 UTC, jamie9504 commented on front-end/legeno-around-here/src/components/pages/JoinPage.js
> +  };
event를 다룰 때, 혹시 모를 이벤트 버블링을 막기 위해서 저는 보통 넣고 있는 것 같습니다.

2020-09-23 13:59 UTC, aegis1920 commented on front-end/legeno-around-here/src/components/pages/JoinPage.js
> +  };
저는 event 인자를 받을 필요가 없는 부분에는 처음부터 안 받는 방식으로 구현했었는데 혹여나 event를 넣었을 때를 대비해서 받고 event.preventDefault()를 해주는 게 좀 더 방어적인 코드가 될 것 같네요 :)

2020-09-23 14:01 UTC, aegis1920 approved these changes
수고하셨습니다 제이미!

2020-09-23 20:46 UTC, yelimkim98 approved these changes

2020-09-23 20:51 UTC, merged