feat: 법정 구역 구현 [ISSUE-48]
woowacourse-teams/2020-welcome-korea pull request #49
Opened 2020-07-20 07:38 UTC by ihoph

**이슈 번호**

resolved: #48

**작업 내용**

1. Region 정의
2. RegionLevel 정의
3. Regions 정의 및 구현
4. Area 정의
5. LegalArea 정의 및 구현

**테스트 작성 여부**

- [X] Test case

2020-07-20 08:50 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/LegalArea.java
> +
공백이 두 줄이네요 😎

2020-07-20 09:07 UTC, jamie9504 requested changes
안녕하세요~! 제이미입니다!
가장 먼저 개발 PR을 날려주셨네요 👍 
생각을 해보면 좋을 것 같은 부분과 궁금한 부분 코멘트 남겨놨으니 확인 부탁드립니다 😄 
오늘도 좋은 하루되세요~ :)

2020-07-20 09:07 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/LegalArea.java
> +
공백이 두 칸이에요~!

2020-07-20 09:07 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionLevel.java
> +    LEVEL_3
숫자보다는 문자로 쓰는걸 전 더 선호하는데 어떻게 생각하시는지 궁금합니다.
- 예) `LEVEL_1 ` > `LEVEL_ONE`

그리고 Enum 명에 Level이 들어가서 `LEVEL`이라는 말을 빼도 되지 않을까~ 하는 의견입니다.

depth 라는 용어도 좀 괜찮지 않을까 싶네요!

2020-07-20 09:07 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +    }
생성자에서 생성할 때, 유효성 검사도 했으면 좋겠어요.

- 예) Level_1인 것이 두 번 들어오지 않았는지

2020-07-20 09:07 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +        return regions.size() - DIRRERENCE_BETWEEN_INDEX_AND_SIZE;
DIRRERENCE => `DIFFERENCE` 인 것 같아요!
어차피 불변 객체라면, 이건 메서드가 아니라 필드로 관리해도 될 것 같아요.

2020-07-20 09:07 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionsTest.java
> +}
Test 메서드 네이밍 컨벤션 한 번 확인해주세요~

2020-07-20 09:07 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +    }
생성자에서 List를 한 번 정렬해서 정렬한 채로 들고 있는게 더 좋을 것 같아요.
(작업횟수 대비)

생성자에서 저장할 때 `Collections.unmodifiableList()`로 방어적으로 작성해주면 어떨까요?

2020-07-20 09:07 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/LegalAreaTest.java
> +    }
Given When Then에 맞춰 엔터를 넣어주면 더 보기 좋을 것 같아요~

2020-07-20 09:07 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionLevelTest.java
> +    @DisplayName("정렬 학습")
학습 테스트라서 학습을 넣어놓으신건지 궁금하네요, 정렬 확인 정도로 해주셔도 될 것 같아요!

2020-07-20 09:07 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionTest.java
> +        assertThat(regionLevelThree).isNotNull();
같은 내용을 세 번 테스트하는 이유가 궁금합니다.

(RegionLevel에서 3개로 나뉘긴 하는데, 타입으로 보면 동일한 것 같아요)

2020-07-20 09:12 UTC, aegis1920 reviewed
안녕하세요 루트!
코드에 대한 첫 코멘트네요 ㅎㅎ
몇 가지 피드백 남겼으니 확인부탁드립니다~

2020-07-20 09:12 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Region.java
> +    private final String name;
Region에 대한 name도 객체로 만드는 게 좋지 않을까요? name에 대한 길이도 validate할 수 있으면 좋을 것 같아요!

2020-07-20 09:12 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionTest.java
> +    void counstruct() {
오타난 것 같아요!
```suggestion
    void construct() {
```

2020-07-20 09:12 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionLevel.java
> +public enum RegionLevel {
RegionLevel이라는 enum에서 이미 Level이라는 것을 명시해주고 있기 때문에 `LEVEL_`을 빼도 괜찮을 것 같아요!

2020-07-20 09:12 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionTest.java
> +        Region regionLevelOne = new Region("서울시", RegionLevel.LEVEL_1);
생성자는 하나만 테스트해도 괜찮지 않을까요?

2020-07-20 09:12 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionsTest.java
> +    void getSmallestRegion() {
테스트 네이밍 규칙을 지켜주면 좋을 것 같아요!

2020-07-20 09:12 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionLevelTest.java
> +        List<RegionLevel> regionLevels = Arrays.asList(RegionLevel.LEVEL_1,
`LEVEL_1`을 아래로 내리면 가독성이 더 좋아질 것 같아요!! 
```suggestion
        List<RegionLevel> regionLevels = Arrays.asList(
        RegionLevel.LEVEL_1,
```

2020-07-20 09:16 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionLevel.java
> +    LEVEL_3
오 depth 괜찮은데요

2020-07-20 09:16 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +    }
넵

2020-07-20 09:17 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +        return regions.size() - DIRRERENCE_BETWEEN_INDEX_AND_SIZE;
오타 수정 감사합니다
아하 그런가요 수정해보겠슴다

2020-07-20 09:17 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionsTest.java
> +}
넵

2020-07-20 09:17 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +    }
오 좋은것같네요 반영해보겠습니다

2020-07-20 09:17 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/LegalAreaTest.java
> +    }
넵

2020-07-20 09:18 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionTest.java
> +        assertThat(regionLevelThree).isNotNull();
동일한 테스트이긴 하지만, 코워커들한테 RegionLevel 1이 예를 들어 무엇인지 설명하는 것에 좋을 것 같아서 세번 했습니다

2020-07-20 09:18 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Region.java
> +    private final String name;
넵

2020-07-20 09:18 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionTest.java
> +    void counstruct() {
감사함다

2020-07-20 09:18 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionLevel.java
> +public enum RegionLevel {
넵

2020-07-20 09:19 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionTest.java
> +        Region regionLevelOne = new Region("서울시", RegionLevel.LEVEL_1);
Level에 따라 Region이 어떤 식으로 다른건지 처음 코드를 보는 사람이 이해하기 좋을 것 같아 세번 했습니다

2020-07-20 09:19 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionLevelTest.java
> +        List<RegionLevel> regionLevels = Arrays.asList(RegionLevel.LEVEL_1,
넵

2020-07-20 09:19 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionsTest.java
> +    void getSmallestRegion() {
넵

2020-07-20 12:10 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +}
현재 추상클래스 Area 에 regions 객체가 필드로 들어있는데 getSmallestRegion() 은 추상메서드로 들어있습니다.

그런데 Area 의 getSmallestRegion() 은 Regions 객체에 대한 의존 메서드로 보여집니다. regions가 Area 에 있는 한 getSmallestRegion() 의 구현이 항상 `    Region getSmallestRegion() { return regions.getSmallestRegion(); }` 일 것으로 보입니다. 따라서 자식 클래스에게 전가할 이유가 없다고 생각합니다.

**제안 1**
Area에 regions 를 필드로 두고 getSmallestRegion() 를 abstract Area 클래스에서 구현한다.
```
abstract class Area {

    protected Regions regions;

    Area(Regions regions) {
        this.regions = regions;
    }

    Region getSmallestRegion() {
        return regions.getSmallestRegion();
    }
}
```
```
class LegalArea extends Area {

    LegalArea(Regions regions) {
        super(regions);
    }

    LegalArea(List<Region> regions) {
        super(new Regions(regions));
    }
}
```

**제안 2**
Regions 를 따로 두지 않고, Area 를 region 의 1급컬렉션으로 사용한다.
이 제안은 Regions 객체에 대한 코멘트를 참고해주세요.
```
abstract class Area {

    private static final int DIFFERENCE_BETWEEN_INDEX_AND_SIZE = 1;

    protected final List<Region> regions;

    Area (List<Region> regions) {
        this.regions = regions;
    }
    
    abstract Region getSmallestRegion();
}
```

```
class LegalArea extends Area {

    LegalArea(List<Region> regions) {
        super(new Regions(regions));
    }

    Region getSmallestRegion() {
        Collections.sort(regions);
        return regions.get(getLastIndex());
    }
}
```

2020-07-20 12:10 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +    }
Regions 에 양천구, 노원구, 강남구가 동시에 들어가는 경우에 대해 validation 이 필요해 보입니다.

하지만 Regions 라는 클래스 이름에 대해 이런 validation 은 어울리지 않습니다.
양천구, 노원구, 강남구 리스트도 Region 들의 목록이니까요.

그런데 만약 Regions 의 이름이 Area가 된다면 어떨까요?
Area 를 나타내는 데에 양천구, 노원구, 강남구가 함께 들어있는 것은 이상하므로 validation 이 잘 어울립니다.

게다가 현재 코드에서는 Area 에 존재하는 필드가 regions 밖에 없습니다.
만약 Area가 상속구조를 사용하지 않고
법정Area인지 행정상Area인지 도로명Area인지를 필드로 갖는다면
Area 와 Regions 의 분리가 올바를 것입니다.

하지만 현재의 상속구조를 따른다면 이런 필드는 생기지 않습니다.
그리고 regions 에 대한 모든 연산은 사실상 regions에게 맡기게 될 것입니다.
이는 getSmallestRegion() 기능이 regions 에게 맡겨지고있는 것에서도 알 수 있습니다.
그렇다면 Area와 Regions 를 따로 가져갈 이유가 있을까요?

**제안**
이는 앞서 abstract class Area 부분에 남긴 코멘트의 제안 2번과 같습니다.
```
abstract class Area {

    private static final int DIFFERENCE_BETWEEN_INDEX_AND_SIZE = 1;

    private final List<Region> regions;

    Area (List<Region> regions) {
        this.regions = regions;
    }
    
    abstract Region getSmallestRegion();
}
```

```
class LegalArea extends Area {

    LegalArea(List<Region> regions) {
        super(new Regions(regions));
    }

    Region getSmallestRegion() {
        Collections.sort(regions);
        return regions.get(getLastIndex());
    }
}
```

2020-07-20 12:10 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +    private static final int DIRRERENCE_BETWEEN_INDEX_AND_SIZE = 1;
혹시 difference 의 오타인가요?

2020-07-20 12:10 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionLevel.java
> +}
LEVEL_1, LEVEL_2, ... 가 무슨 의도로 사용된 용어인지 알 수 없습니다.

만약
서울시, 충청남도 : level1
양천구, 천안시 : level2
이런식이라면
Level 보다는 Depth 를 사용하는 것도 좋을 것 같습니다.
자료구조 가운데 행정구역에 가장 잘 들어맞는 것이 트리구조이고
depth 가 tree 의 깊이를 잘 표현한다고 생각합니다.

혹은 
LEVEL1, 2, 3 
이런 표기 대신 
도, 시, 군, 구, 읍, 자체로 enum 을 가져갈 수 있을 것도 같습니다.
```
public enum RegionType {
    DO,    // 도
    CITY,    // 시
    ...
}
```

2020-07-20 16:57 UTC, Hamliet approved these changes
다른 분들이 남긴 리뷰 외에 추가로 남길 부분이 없어 Approve 하겠습니다. 수고하셨습니다.

2020-07-21 01:19 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionTest.java
> +        Region regionLevelOne = new Region("서울시", RegionLevel.LEVEL_1);
같은 로직을 세 번 테스트 한다면 `@ParameterizedTest`를 사용해도 좋을 것 같네요 :)

2020-07-21 05:09 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +}
제안 1에 대하여: 책 오브젝트에 따르면, 자식 클래스는 부모 클래스의 구현에 의존하면 안된다고 합니다. 이러한 점에서 필드도 private으로 두거나 하는게 좋을 수도 있죠. getSmallestRegion()를 Area에 둔다면 LegalArea는 Area의 구현에 의존하게 됩니다.이렇게 되면 LegalArea가 아닌 AdministrativeArea와 같은 다른 자식이 생길 때, 문제가 될 수 있을 것 같습니다. 

제안 2에 대하여: [이 글](https://jojoldu.tistory.com/412)에 따르면, Collection을 Wrapping하면서, 그 외 다른 멤버 변수가 없는 상태를 일급 컬렉션이라고 한다고 합니다. 즉 Area가 List<Region>을 갖는다면 일급컬렉션이 아니게 되는 것이죠.
Regions를 두지 않는게 좋다고 생각하시는 이유가 있나요? 설명해주시면 감사하겠습니다.

2020-07-21 05:10 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +    }
잘 이해가 안돼서, 구두로 설명해주시면 감사하겠습니다.

2020-07-21 05:27 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/LegalArea.java
> +
오... 감사함다
포맷팅을 적용해도 이건 안잡아주네요 ㅜ

2020-07-21 06:38 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +}
부모 클래스에서 final 메서드를 정의하면
자식 클래스에서 같은 메서드를 구현한것과 같은바로 알고있습니다.

모든 자식들에서 오버라이딩 코드가 똑같아져서 중복이 될것이기 때문에
부모에서 구현하는것이 맞는것으로 보입니다.

2020-07-22 13:24 UTC, jamie9504 requested changes
안녕하세요 루트 :)

팀원들의 저번 리뷰를 신경쓰셔서 반영해주신 것 같아요! 👍 

수정한 사항 관련해 리뷰를 조금 더 남겨두었습니다~!

2020-07-22 13:24 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +        .format("region의 갯수가 최소 갯수인 %d보다 작습니다.", MIN_SIZE);
저는 예외 메세지의 경우엔 상수화를 하지 않는데, 이 부분은 개인 취향인 것 같아요 😄

2020-07-22 13:24 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +        Map<RegionDepth, Region> regions) {
엔터를 치신 이유가 있으실까요❔

2020-07-22 13:24 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/LegalAreaTest.java
> +
여기도 DisplayName이 달리면 좋겠네요!

2020-07-22 13:24 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionNameTest.java
> +    void construct_nameLengthUnder1OrOver10_throwIllegalArgumentException() {
테스트의 경우, 0글자인 경우만 테스트가 되고 있어요!

메서드명을 변경하시거나, ParameterizedTest를 이용해보는 건 어떨까요 😉

2020-07-22 13:24 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionName.java
> +                INVALID_LENGTH_ERROR);
여기도 엔터 제거해주셔도 될 것 같아요~!

2020-07-22 13:24 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +}
저는 대부분의 객체(Entity or VO or Dto)는 toString을 오버라이딩해야 한다고 생각하는데요!
디버깅시 toString이 없으면 불편하더라구요, 혹시 어떻게 생각하시나요?

+ 이펙티브 자바 12장

2020-07-22 13:24 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +    }
RegionDepth가 같은 것이 들어오는지도 검증이 되면 좋을 것 같아요!

2020-07-22 13:24 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +            .reduce((depth1, depth2) -> depth1.compareTo(depth2) > 0 ? depth1 : depth2)
오랫만에 보는 삼항 연산자네요 ! 😄

2020-07-23 04:15 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +    }
Map이라서 RegionDepth가 겹칠 수 없는 것 같던데여??

2020-07-23 04:15 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +}
멀랐어여.. 전 toString을 잘 안쓰는데 toString 적용하겠습니다~

2020-07-23 04:20 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionName.java
> +                INVALID_LENGTH_ERROR);
제거했습니다~

2020-07-23 04:31 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +    }
맞네요! 이 부분을 체크하지 못했습니다~! :)

2020-07-23 04:46 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionLevelTest.java
> +    @DisplayName("정렬 학습")
변경했습니다!

2020-07-23 04:47 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +        .format("region의 갯수가 최소 갯수인 %d보다 작습니다.", MIN_SIZE);
이 부분은 테스트할 때 좋은점이 있는 것 같아 상수화해봤습니다!

2020-07-23 04:48 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +        Map<RegionDepth, Region> regions) {
아뇨 딱히 없습니다 자동완성하니까 저렇게 됐습니다! 엔터 없앴습니다~

2020-07-23 04:51 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/LegalAreaTest.java
> +
네 반영했습니다~

2020-07-23 04:53 UTC, ihoph commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionNameTest.java
> +    void construct_nameLengthUnder1OrOver10_throwIllegalArgumentException() {
ParameterizedTest 적용해봤습니다~

2020-07-23 04:54 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +            .reduce((depth1, depth2) -> depth1.compareTo(depth2) > 0 ? depth1 : depth2)
단순한 연산인 것 같아 삼항연산자를 적용해보기 좋아보여서 적용해봤습니다!

2020-07-23 05:01 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Regions.java
> +    }
Regions를 없애봤습니다~

2020-07-23 05:01 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +}
부모에서 구현하는 것으로 수정했습니다~

2020-07-23 07:24 UTC, aegis1920 requested changes
사소한 피드백 몇 가지 남겼습니다!

2020-07-23 07:24 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/area/RegionNameTest.java
> +    }
아주 사소한 테스트 네이밍 컨벤션 :) 
```suggestion
    void construct_NameLengthUnder10OrOver1_Constructed() {
        RegionName regionName = new RegionName("홍제동");
        assertThat(regionName).isNotNull();
    }

    @DisplayName("1글자 미만, 10글자 초과의 글자를 활용한 RegionName 생성 - 실패")
    @ParameterizedTest
    @ValueSource(strings = {"", "10자이상의RegionName"})
    void construct_NameLengthUnder1OrOver10_ThrowIllegalArgumentException(String regionName) {
        assertThatThrownBy(() -> new RegionName(regionName))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessage(RegionName.INVALID_LENGTH_ERROR);
    }
```

2020-07-23 07:24 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/Area.java
> +    }
stream()의 max() 함수를 사용하면 더 줄일 수 있을 것 같아요 :)
```suggestion
    Region getSmallestRegion() {
        RegionDepth smallestRegionDepth = regions.keySet().stream()
            .max(RegionDepth::compareTo)
            .orElseThrow(() -> new IllegalStateException("Region이 존재하지 않습니다."));
        return regions.get(smallestRegionDepth);
    }
```

2020-07-23 09:59 UTC, yelimkim98 reviewed
피드백 반영 잘 해주셨네요! 가벼운 피드백 추가로 남겼습니다. 여기까지 완료되면 approve 하겠습니다!

2020-07-23 09:59 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/LegalArea.java
> +        Map<RegionDepth, Region> regions) {
줄바꿈이 없어도 될것같아요 :)

접근제어자가 protected 인 이유가 있나요?? 생성자가 protected 이면 LegalArea 객체를 생성할 수 없을것같아요.

2020-07-24 03:46 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/area/LegalArea.java
> +        Map<RegionDepth, Region> regions) {
딱히 이유 없이 자동 생성했더니 protected가 됐습니다~ public으로 수정했습니다

2020-07-24 04:48 UTC, yelimkim98 approved these changes

2020-07-24 05:17 UTC, aegis1920 approved these changes
덕분에 더 실력향상이 된 것 같습니다!
수고하셨습니다!! 👍

2020-07-24 05:17 UTC, jamie9504 approved these changes
Approve 하겠습니다 :)

2020-07-24 05:18 UTC, merged