feat: 월간 인기글 랭킹 Top 3 수상 기능 구현 [ISSUE-324]
woowacourse-teams/2020-welcome-korea pull request #505
Opened 2020-10-05 19:06 UTC by yelimkim98

**이슈 번호**

resolved: #324 

**작업 내용**

1. 월간 인기글 랭킹 Top 3 수상 기능 구현
2. RankingCriteria 지난달, 지난주, 어제 계산 구현 잘못된 부분 수정
3. 테스트 코드 보강

**테스트 작성 여부**

- [X] Test case

**주의 사항**

2020-10-08 14:00 UTC, aegis1920 requested changes
히히 수고했어요~ 몇 가지 피드백 남겼으니 확인해주세요 :)

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +            + "위";
이 부분은 `+` 연산자가 많아서 `StringBuilder`를 써도 좋겠네요 :)

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +                + endDate.getDayOfMonth() + "일"
여기도 마찬가지 StringBuilder!

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/AwardController.java
> +    private final AwardReadService awardReadService;
`AwardService`가 클래스명에 더 맞지 않을까요?

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        if (rankingCriteria.equals(RankingCriteria.LAST_MONTH)) {
`rankingCriteria`에게 메시지를 보내도 될 것 같아요 :)

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        throw new UnsupportedOperationException("월간 수상만 지원합니다.");
예외 메시지를 보낼 때 현재 어떤 상태인지도 보내주면 예외를 더 정확히 파악할 수 있을 것 같아요 :)

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        throw new UnsupportedOperationException("월간 수상만 지원합니다.");
현재 `GlobalExceptionHandler`에 `UnsupportedOperationException`가 없어요!
추가해야될 것 같네요 :)

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        if (startDate.getMonthValue() + 1 != endDate.getMonthValue()) {
요기서 `1`에 대한 매직넘버를 상수화를 해주면 그 의미를 좀 더 빠르게 파악할 수 있겠네요 :)

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/scheduler/PostAwardCreateScheduler.java
> +    @Scheduled(cron = "0 0 0 1 * *")    // cron : 0초 0시 0분 1일 *월 *요일 (매월 1일 0시 0분 0초)
주석으로 쉽게 이해했어요! 👍

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/scheduler/PostAwardCreateScheduler.java
> +    private PopularPostAwardService popularPostAwardService;
`final`을 붙여도 될 것 같네요!

2020-10-08 14:00 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/AreaService.java
> +        return Collections.unmodifiableList(areaRepository.findAll());
혹시 불변으로 해준 이유가 있을까요? 궁금합니다!

2020-10-08 14:00 UTC, aegis1920 commented on front-end/legeno-around-here/src/components/myProfile/PrivacySection.js
> +  cursor: pointer
세심하네요ㅎㅎ 👍

2020-10-09 06:42 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +            + "위";
이부분 원래 StringBuilder를 써서 구현했었는데요..! 인텔리제이가 String 으로 할것을 추천하더라구요..?
![image](https://user-images.githubusercontent.com/28949340/95550620-27664600-0a44-11eb-8dfd-1a6e664b3d12.png)

그래서 String 과 StringBuilder 를 사용할 때 차이를 찾아봤는데
명확한 해답은 못찾았지만
지금 상황에서는 큰 차이가 없을 것 같다고 생각되더라구요..!

참고
1.
작은양의 "+" 연산은 오히려 StringBuilder를 사용하는 것이 안좋다고 한다.

https://m.blog.naver.com/PostView.nhn?blogId=bluelevel&logNo=70130739583&proxyReferer=https:%2F%2Fwww.google.com%2F

2.
`'StringBuilder' can be replaced with 'String'` 은 결과 연결이 최소한 원래 코드보다 효율적이거나 더 효율적인 경우 만보고합니다. StringBuilder를 String으로 대체하는 것은 일반적으로 효율적이지만 코드는 더 명확하고 읽기 쉽습니다.

(Inspection 'StringBuilder' can be replaced with 'String' only reports the cases when the resulting concatenation is at least as efficient or more efficient than the original code. Replacing the StringBuilder with a String would be usually just as efficient, but the code would be more clear and readable. )

https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000093250-Convert-StringBuilder-to-String-concatenation-suggestion

2020-10-09 06:49 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/AwardController.java
> +    private final AwardReadService awardReadService;
지금 AwardReadService 에는 상을 주는 메서드는 없고 상을 find 하는 기능만 있는데요!
그래서 이름을 이렇게 지은거였는데 저도 뭔가 좀 아쉽긴 했습니다...

AwardReadService의 목적은 부문 창시상과 인기글 상을 한번에 '상'이라는 리스트로 가져오는 역할인데요..!

얘를 없애자니 AwardController가 로직을 갖게되고 해서 놔두긴 했지만
뭔가 좀 마음에 안들긴 하더라구요...

2020-10-09 07:43 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/AwardController.java
> +    private final AwardReadService awardReadService;
코멘트를 읽고나니
AwardReadService 라고 할거면
AwardController 가 AwardReadController 가 되어야 한다는 생각이 들었습니다..!

한편으로는 이 설계가 좀 마음에 안드실 수 있을 것 같다는 생각도 듭니다.
(저는 좀 맘에 안듭니다..)

맘에 안드는 면을 해결하려면 공을 좀 많이 들이긴 해야할 것 같습니다...

2020-10-09 08:18 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +            + "위";
적은 양의 "+" 연산이 아닌 것 같아서 이야기했었는데 링크해주신 곳에서 답변을 보니 반복문을 쓰면 StringBuilder를 사용하고 아니면 String을 쓴다고 하네요 :)
깨달음 주셔서 감사합니다 👍 👍

2020-10-09 08:30 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/AwardController.java
> +    private final AwardReadService awardReadService;
개인적으로는 아예 `SectorService`와 `PopularPostAwardService`에 있는 내용을 모두 `AwardService`에 옮겨도 될 것 같다고 생각이 드네요!
그리고 `AwardReadService` 가 된다면 읽는 역할만 가지게 될텐데 확장성 측면에서 너무 닫혀있지 않을까요?

+ 친절한 설명 감사합니다ㅎㅎ 덕분에 이해가 잘 됐어요!

2020-10-09 08:31 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/AreaService.java
> +        return Collections.unmodifiableList(areaRepository.findAll());
저는 특별히 불변이 아니어야할 상황을 제외하면 모두 불변을 사용하고자 합니다!

all areas를 검색한 뒤에 이 리스트에 뭔가 다른 element를 붙인다면
그 리스트는 더이상 all areas 가 아니게 될 수 있습니다.

그런 코드는 읽는 사람도 불편하고
코드 짜는 사람도 실수하게 만드는 코드라고 생각합니다.

프로그래밍할떄 조금이라도 덜 실수하게 해주는 장치인 것입니다!

2020-10-09 08:31 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        if (rankingCriteria.equals(RankingCriteria.LAST_MONTH)) {
`rankingCriteria.isSame(RankingCriteria.LAST_MONTH)`
이것과
`rankingCriteria.equals(RankingCriteria.LAST_MONTH)`
이것의 차이가 없다고 느껴집니다..!

객체에 메세지를 보내자는 측면에서 지금 코드가 문제 없다고 생각합니다!!

2020-10-09 08:31 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        throw new UnsupportedOperationException("월간 수상만 지원합니다.");
그렇네요!! 수정했습니다!

2020-10-09 08:31 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        throw new UnsupportedOperationException("월간 수상만 지원합니다.");
지금 사실상 AwardNameMaker 는 스케쥴링에서만 사용되고 있고 컨트롤러와는 무관한데 의미가 있을지 모르겠습니다..
확실히 스케쥴러에서 UnsupportedOperationException 에 대한 처리가 일어나지 않고있어서 문제네요!
반영해보겠습니다!

2020-10-09 08:48 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/AwardController.java
> +    private final AwardReadService awardReadService;
`SectorService`에 있는 내용을 `AwardService`로 옮기려면

부문 상태를 Pending 상태에서 Approved 상태로 바꾸는 일을
`AwardService`가 하게됩니다..

그렇게 할 순 없으니 `SectorService` 에서 부문 창시 상을 만드는 것을 피할 수 없습니다..


그렇다고 `PopularPostAwardService` 에 있는 내용만 `AwardService` 로 옮기자니
부문 창시상은 `SectorAwardService` 에서 만들고 인기글 창시상은 `AwardService` 에서 만들면
통일성이 없어지는 것 같습니다..

수상 관련 로직은
1. 상을 만들거나
2. 상을 읽거나
이 두가지인데,
`AwardReadService` 가 상을 만드는 기능을 가지면 순환참조가 발생하며 문제가 생겨버리니
확장을 할 수 없는 부분이 아닌가 생각됩니다..

2020-10-09 08:55 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        if (startDate.getMonthValue() + 1 != endDate.getMonthValue()) {
확실히 if 조건절 가독성이 안좋네요..!

매직넘버 `1` 에 대해 도저히 어떤 의미를 부여하기가 어려워서
이 부분을 메서드로 추출해 보았습니다!

2020-10-10 08:10 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        if (rankingCriteria.equals(RankingCriteria.LAST_MONTH)) {
엇 저는 RankingCriteria에 메서드를 만드는 걸 생각했습니다! `rankingCriteria.isLastMonth()` 처럼요!

2020-10-10 08:17 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        throw new UnsupportedOperationException("월간 수상만 지원합니다.");
아 그러네요! 서버에서만 사용되니 사용자에게 보여줄 필요가 없네요! 그렇다면 예외를 던지고 로깅만 해줘도 될 것 같다는 생각도 드는데 어떻게 생각하시나요?

2020-10-10 08:25 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/AreaService.java
> +        return Collections.unmodifiableList(areaRepository.findAll());
좋네요! 특히 find한 경우에 붙이는 건 더 좋은 습관이라고 생각이 들었어요 :) 설명 감사합니다!

2020-10-10 08:43 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/AwardController.java
> +    private final AwardReadService awardReadService;
헉 죄송합니다ㅠㅠ `SectorService`가 아니라 `SectorAwardService`와 `PopularPostAwardService`를 말한 거였어요!!

2020-10-10 18:24 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/AwardController.java
> +    private final AwardReadService awardReadService;
그렇게하면 순환참조가 발생합니다..
AwardService 에서
모든 부문과 모든 지역에 대해 상을 주기 위해서
모든 부문과 모든 지역을 가져옵니다.
이 때 모든 부문을 가져오기 위해서 SectorService 에 의존합니다.

그런데 SectorService는
pending 상태의 부문을 approved 로 바꾸는 기능이 있습니다.
이 기능이 동작할 때 부문 창시상이 생성되기 때문에
SectorService 가 AwardService 에 의존하게됩니다..

2020-10-10 18:40 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        if (rankingCriteria.equals(RankingCriteria.LAST_MONTH)) {
앗 그렇군요!! 이해했습니다!! 맞네요..! 반영하겠습니다!!

2020-10-11 05:27 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/AwardController.java
> +    private final AwardReadService awardReadService;
Service를 의존하지 않고 Repository를 의존해서 구현한다면 순환참조를 없앨 수 있을 것 같은데 이러면 중복되는 코드가 생기는 문제가 있네요. 개인적으로는 중복되는 코드가 생기더라도 AwardService로 만들어서 수상에 대한 모든 책임을 여기에 만드는 게 좋다고 생각하긴 합니다. 어떻게 생각하시나요? 나중에 데일리 때 의견을 나눠봐도 좋구요 :)

2020-10-11 16:11 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        throw new UnsupportedOperationException("월간 수상만 지원합니다.");
handler 에서 캐치 하지않고 예외 던질때 로깅 하자는 뜻 맞나요?!

일단 handler controller 에서
```
@ExceptionHandler({Exception.class, NotFoundAlgorithmException.class})
handleInternalServerError() 
```
에 `UnsupportedOperationException` 을 살포시 추가하고
```
스케쥴러에 이렇게 try-catch 를 추가해봤습니다..!
@Scheduled(cron = "0 0 0 1 * *")    // cron : 0초 0시 0분 1일 *월 *요일 (매월 1일 0시 0분 0초)
    public void createPopularPostAwards() {
        try {
            popularPostAwardService.createPopularPostAwards(LocalDateTime.now());
        } catch (Exception e) {
            log.error(e.getMessage());
        }
    }
```

2020-10-12 05:30 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/util/AwardNameMaker.java
> +        throw new UnsupportedOperationException("월간 수상만 지원합니다.");
사용자에게 보여줄 필요가 없기 때문에 `controllerAdvice`에서 잡지 않아도 될 것 같아요 :) 오히려 서버의 에러는 사용자에게 보여주면 안되기도 하고요!
그리고 로깅할 때는 저희가 예측하고 있는 예외라면 로깅 레벨을 INFO로 주셔도 됩니다! + 자세한 로깅을 위해서 e.getMessage가 아니라 e를 주는 게 더 좋아요!

2020-10-12 18:35 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/AwardController.java
> +    private final AwardReadService awardReadService;
PopularPostAwardService가 SectorService에 의존하는 대신 SectorRepository에 의존하도록 변경하여
구조를 개선해 보았습니다!!

2020-10-15 09:32 UTC, aegis1920 approved these changes
피드백을 잘 반영해주셨네요! 수고하셨습니다!

2020-10-15 12:17 UTC, merged