feat: 회원가입 구현 [ISSUE-2]
woowacourse-teams/2020-welcome-korea pull request #53
Opened 2020-07-21 08:57 UTC by Hamliet

**이슈 번호**

resolved: #2 

**작업 내용**

1. 유저 인수테스트 작성
2. 유저 컨트롤러 테스트, 컨트롤러 구현 (회원가입 부분)
3. 유저 서비스 테스트, 서비스 구현 (회원가입 부분)
4. User 클래스 정의
5. UserRepository 정의 및 JPA 연동

**테스트 작성 여부**

- [X] Test case

**주의 사항**
닉네임, 비밀번호 포맷 검증을 다음과같이 구현했는데 이견 있으시면 피드백 부탁드립니다.
1. 닉네임
    - 10글자 이하
    - 공백 포함 불가
2. 비밀번호
    - 8 ~ 16 자

2020-07-21 09:48 UTC, ttkmw approved these changes
저와 코딩 스타일이 되게 비슷한거같네요
저는 남길게 많이 없어서 바로 어프루브합니다

2020-07-21 09:48 UTC, ihoph commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Password.java
> +            throw new IllegalArgumentException("비밀번호는 8 ~ 16 자여야 합니다.");
8, 16도 위의 상수를 쓰는 게 좋을 것 같습니다

2020-07-21 16:15 UTC, aegis1920 requested changes
안녕하세요! 히히, 라흐 :)
열심히 코드 작성해주셨네요! 수고하셨습니당ㅎㅎ
몇 가지 피드백 남겼으니 확인해주세요~

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/NickName.java
> +public class NickName {
혹시 단순하게 Nickname은 어떤가요? ㅎㅎ

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Password.java
> +            throw new IllegalArgumentException("비밀번호는 8 ~ 16 자여야 합니다.");
저도 루트의 의견과 같습니다! 위에 선언되어 있는 상수를 그대로 쓰면 될 것 같아요 :)

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    public User() {
엔티티 기본 생성자의 접근제한자는 `protected`로 설정하는 것이 안전성 면에서 더 좋다고 생각합니다 :)

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    }
Email, NickName, Password 등 각 객체를 생성할 때 `validateNull()`이라는 메서드로 먼저 Null을 검증하지 않나요?

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserCreateRequest.java
> +    }
바로 return 해줘도 괜찮을 것 같아요!
```suggestion
    public User toUser() {
        return new User(
            new Email(this.email),
            new NickName(this.nickName),
            new Password(this.password)
        );
    }
```

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptanceTest/UserAcceptanceTest.java
> +        assertThat(location).matches(USER_LOCATION_FORMAT);
회원 가입을 하고 나서 그 회원이 제대로 가입됐는지 확인이 필요하지 않을까요?

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/constants/UserTestConstants.java
> +    public static final Long TEST_ID = 1L;
중복해서 쓰이는 부분을 잘 분리해주셨네요 👍

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/domain/user/EmailTest.java
> +    void constructor_IfEmailIsNull_ThrowException() {
테스트 함수 네이밍이 눈에 잘 들어오네요 💯

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/UserServiceTest.java
> +        verify(userRepository).save(any());
`verify()`는 그 함수가 실행됐는지만 물어봅니다.
`verify()`만으로는 'User가 생성됐는지 테스트' 했다고 보기 어려울 것 같습니다 :)
Mock 테스트라면 `when()` 과 `thenReturn()`을 통해 Mock을 `return`시켜 해당 return 값을 테스트하는 건 어떨까요?

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/NickName.java
> +            throw new IllegalArgumentException("닉네임은 10글자 이하여야 합니다.");
예외 String 부분에 10을 `MAX_LENGTH`로 바꿔도 좋을 것 같아요!

2020-07-21 16:15 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
`GenerationType.AUTO`로 설정하더라도 DB에 맞게 전략이 항상 같게 맞춰지지 않습니다!
스프링부트의 버전(Hibernate 버전)과 DBMS의 종류에 따라 달라지는데요!

> 스프링부트 2.0에선 '스프링부트가 Hibernate를 따라가는 설정값'이 true이므로 Hibernate 5를 그대로 따라갑니다.
Hibernate 5.0부터 MySQL의 AUTO는 IDENTITY가 아닌 TABLE을 기본 시퀀스 전략으로 선택됩니다.


이러한 이유에서 MySQL을 사용하고, SpringBoot의 버전을 2.0이상 사용하면서, AutoIncrement를 사용하고 싶다면 `GenerationType.IDENTITY` 을 사용하는 것이 맞습니다.

참고내용 : https://jojoldu.tistory.com/295

2020-07-21 16:24 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/NickName.java
> +public class NickName {
nickname이 한 단어네요 ..!!! 😅 수정하겠습니다 !

2020-07-21 16:25 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Password.java
> +            throw new IllegalArgumentException("비밀번호는 8 ~ 16 자여야 합니다.");
해당 부분 반영하겠습니다!

2020-07-21 16:25 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    public User() {
동의합니다. 수정하겠습니다!

2020-07-21 16:27 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    }
각 객체에서는 String 에 대한 Null 검증이고 여기는 각각의 객체에 차제에 대한 Null 검증입니다. 
User를 생성할 때 발생할 수 있는 모든 Null을 잡아줘야 한다고 생각해서 작성했습니다.

2020-07-21 16:35 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/NickName.java
> +            throw new IllegalArgumentException("닉네임은 10글자 이하여야 합니다.");
수정하겠습니다 ㅎㅎ

2020-07-21 16:39 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
신경쓰지 않고 사용했었는데 이런 문제점이 있었군요! 좋은 정보 감사합니다 ㅎㅎ! 반영하겠습니다~

2020-07-22 06:21 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserCreateRequest.java
> +    }
반영했습니다!

2020-07-22 06:31 UTC, aegis1920 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    }
저는 개인적으로 null validation은 '값이 잘못 들어갈 수 있는 사용자의 입력'과 같이 null이 할당될 수 있는 곳이거나 null에 접근할 가능성이 있는 로직에 해야 된다고 생각합니다.

현재 new User()에 들어가는 인자들은 사용자의 input이 아닌 인자들입니다. new User()에 들어가는 인자, 즉, 각 객체(Email, NickName, Password)들은 이미 null에 대한 validation이 끝났습니다.

개발자가 new User()에 일부러 null을 할당하지 않는 한 해당 변수에 null이 들어갈 일은 없으며 만약 이를 위해 null validation을 작성해야 한다면 new User() 뿐만 아니라 인자가 존재하는 모든 함수에 null validation을 적용해야 될 것입니다.

2020-07-22 07:21 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/acceptanceTest/UserAcceptanceTest.java
> +        assertThat(location).matches(USER_LOCATION_FORMAT);
추후 조회 기능 구현 후 테스트 완성하도록 하겠습니다. ;)
대신 주석 `Todo`로 남겨두겠습니다.

2020-07-22 07:36 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/service/UserServiceTest.java
> +        verify(userRepository).save(any());
@DataJpaTest 로 수정해서 실제로 User 리턴받는 지 확인했습니다.

2020-07-22 07:39 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Password.java
> +            throw new IllegalArgumentException("비밀번호는 8 ~ 16 자여야 합니다.");
수정했습니다!

2020-07-22 12:41 UTC, jamie9504 requested changes
안녕하세요 JAMIE 입니다~!

라흐&히히 페어의 첫 개발 PR이네요!
메서드명도 테스트도 다 술술 잘 익혔습니다. 💯 
얘기를 나눠보고 싶은 부분과 수정했으면 하는 부분을 남겨놓았으니 참고 부탁드려요 😄

2020-07-22 12:41 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Email.java
> +        Pattern pattern = Pattern.compile(EMAIL_FORMAT);
Pattern은 만드는데 비용이 커서, 상수화 하는 것이 좋다고 했던 것 같아요 :)

2020-07-22 12:41 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Email.java
> +}
toString()이 객체마다 들어가면 좋을 것 같아요!
객체에 toString()을 재정의해놓으면 디버깅시 매우 용이합니다.

- 이펙티브 자바 12장

2020-07-22 12:41 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    private Long id;
추후에 이 부분은 Post쪽 PR 되면 BaseEntity를 상속받도록 하면 좋겠네요~!

2020-07-22 12:41 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +    public User createUser(User user) {
Method나 Class에 @Transactional을 적용해보는 건 어떨까요? 😉

2020-07-22 12:41 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Email.java
> +}
JPA에서, 값 객체의 경우 (@Embeddable) equals와 hashcode를 오버라이딩해줘야 합니다~!
- JPA 책 9장

2020-07-22 12:41 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/UserController.java
> +        User user = userService.createUser(userCreateRequest.toUser());
전 Controller에서는 dto를, Service에서는 domain을 관리하자는 생각인데 어떻게 생각하시는지 궁금하네요 😄

2020-07-22 12:41 UTC, jamie9504 commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/controller/UserControllerTest.java
> +        given(mockUser.getId()).willReturn(TEST_ID);
mock을 이용한 테스트는 자칫 구현에 얽매일 수 있을 것 같아요. 이 부분도 얘기를 나눠보면 좋겠네요 :)

2020-07-23 08:42 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    }
넵 반영했습니다!

2020-07-23 08:50 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Email.java
> +        Pattern pattern = Pattern.compile(EMAIL_FORMAT);
넹

2020-07-23 08:53 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Email.java
> +}
넹!

2020-07-23 08:54 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/User.java
> +    private Long id;
넵 알겠습니다!

2020-07-23 08:55 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/service/UserService.java
> +    public User createUser(User user) {
반영했습니다!

2020-07-23 09:00 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/domain/user/Email.java
> +}
좋은 피드백 감사합니다ㅎㅎ 역시 제이미! 👍👍👍

2020-07-23 09:06 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/controller/UserController.java
> +        User user = userService.createUser(userCreateRequest.toUser());
우선 createUser는 Long을 리턴하도록 수정하였고, 추후에는 Request, Response로 주고받도록 하겠습니다.

2020-07-23 09:08 UTC, Hamliet commented on back-end/legeno-around-here/src/test/java/wooteco/team/ittabi/legenoaroundhere/controller/UserControllerTest.java
> +        given(mockUser.getId()).willReturn(TEST_ID);
넵!

2020-07-23 10:25 UTC, aegis1920 approved these changes
피드백 반영을 잘 해주셨네요! 💯 
히히와 라흐의 코드를 리뷰하면서 더욱 성장할 수 있었던 것 같습니다 :)
의미있는 토론을 한 것도 좋았고요!
수고하셨습니다!! 👍 👍

2020-07-24 04:25 UTC, jamie9504 requested changes
확인 부탁드려여 :)

2020-07-24 04:25 UTC, jamie9504 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserCreateRequest.java
> +    }
RequestDto의 빈 생성자(기본 생성자)의 경우

@RequestBody 등에서 Reflection을 이용할 때 사용되는데, 이는 private으로 접근 제어자를 변경해도 됩니다!
따로 쓰는 곳이 없다면 private으로 변경하는 것은 어떨까요?

2020-07-24 04:43 UTC, Hamliet commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserCreateRequest.java
> +    }
private으로 가능했군요..!! 반영하겠습니다!!

2020-07-24 04:53 UTC, yelimkim98 commented on back-end/legeno-around-here/src/main/java/wooteco/team/ittabi/legenoaroundhere/dto/UserCreateRequest.java
> +    }
오오 그러쿤요..!

2020-07-24 05:10 UTC, jamie9504 approved these changes
이만 Approve 합니다 😉

2020-07-24 05:13 UTC, yelimkim98 approved these changes

2020-07-24 05:13 UTC, merged